// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmGVZrKht_3NIIBkBWK_k4Aq1qZ_ytWY',
    appId: '1:15785085137:web:ce67b52d3c0b6ef2165df0',
    messagingSenderId: '15785085137',
    projectId: 'b-unique-hrm',
    authDomain: 'b-unique-hrm.firebaseapp.com',
    storageBucket: 'b-unique-hrm.firebasestorage.app',
    measurementId: 'G-MNMCZ9KDGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc3fgOC5xQmyoga85pppPq0EJmrdXx0nk',
    appId: '1:15785085137:android:c94bae63a23f420e165df0',
    messagingSenderId: '15785085137',
    projectId: 'b-unique-hrm',
    storageBucket: 'b-unique-hrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANX4SPXAXOFfrTYty0FaBjX8RfMTtw5Eo',
    appId: '1:15785085137:ios:de3a44f1e7535276165df0',
    messagingSenderId: '15785085137',
    projectId: 'b-unique-hrm',
    storageBucket: 'b-unique-hrm.firebasestorage.app',
    iosBundleId: 'com.example.buniqueStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANX4SPXAXOFfrTYty0FaBjX8RfMTtw5Eo',
    appId: '1:15785085137:ios:de3a44f1e7535276165df0',
    messagingSenderId: '15785085137',
    projectId: 'b-unique-hrm',
    storageBucket: 'b-unique-hrm.firebasestorage.app',
    iosBundleId: 'com.example.buniqueStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLmGVZrKht_3NIIBkBWK_k4Aq1qZ_ytWY',
    appId: '1:15785085137:web:a5f081b696c2a344165df0',
    messagingSenderId: '15785085137',
    projectId: 'b-unique-hrm',
    authDomain: 'b-unique-hrm.firebaseapp.com',
    storageBucket: 'b-unique-hrm.firebasestorage.app',
    measurementId: 'G-ZMEP64WH8K',
  );
}
